spring.application.name=17_web_mvc_thymeleafApp

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=abc
spring.datasource.password=abc
spring.datasource.driver-class-name=org.h2.Driver

